### ISSUE TITLE
Closing connection leads to 'non-deterministic' handleShutdownSignal notification

### ISSUE THREAD

**Issue by wegenmic** [rabbitmq/rabbitmq-java-client#312] opened 2017-10-06 06:12 UTC
This issue is based on https://stackoverflow.com/questions/46428458/rabbitmq-automatic-recovery-on-unexpected-channel-close
Which means that the 4.2.1 version of the rabbitmq-java-client was used.

When it comes to closing connections, RabbitMQ comes with tutorials, for example https://www.rabbitmq.com/tutorials/tutorial-five-java.html Here we see that a connection is simply closed with

`connection.close();`
On the other hand the https://www.rabbitmq.com/api-guide.html says

```
channel.close();
conn.close();
```

> Note that closing the channel may be considered good practice, but isn’t strictly necessary here - it will be done automatically anyway when the underlying connection is closed.

So, at this point I wouldn't expect any big difference whatever approach (tutorial or API guide) I choose. Well, this is where it starts getting weird.

The following section describes the test scenario where I spin up a listener, receive a message and close the connection afterwards, 100 times in sequence.

Only closing the connection always results in a triggered `handleShutdownSignal`. Closing first the channel and then the connection does never trigger `handleShutdownSignal`. But when checking this last use case (closing channel, then the connection) on another dev machine (different hardware, different OS, ...) `handleShutdownSignal` is always triggered. To me this looks like a violation to the description in the javadoc as well as the API Guide. Probably a bug? Maybe you can tell me which behaviour is intended so I can give you a little bit more input about the environment that leads to the unwanted result.

**Comment by acogoluegnes** [comment] 2017-10-06 08:25
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment] 2017-10-06 10:27
@wegenmic tutorials are meant to be brief and cover one topic at a time. Closing channels is not technically necessary when a connection is about to be closed. It does, however, make things explicit.

Without seeing your code we cannot suggest much. Shutdown handlers are always invoked on connections, regardless of the reason (explicitly closed by the user, closed due to a connection-level exception, closed by the server or operator). The operation, however, is asynchronous, especially in the case when the server closes a connection. Combine that with a tight loop and yes, the results can look odd. However nothing has changed in how shutdown signals are dispatched in many years, automatic connection recovery — also a few years old by now — relies on it and if there were any obvious issues, we'd hear about it very often.

Please start a mailing list thread and post the exact steps others can use to reproduce.

**Comment by acogoluegnes** [comment] 2017-10-17 08:33
No corresponding thread on the mailing list after 10+ days, closing.

**Closed by acogoluegnes** 2017-10-17 08:33 UTC
